# Generated by Django 4.0.6 on 2023-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
