# Generated by Django 4.0.6 on 2023-04-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='profile_pic',
        ),
    ]
