# Generated by Django 4.0.6 on 2023-05-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
