# Generated by Django 4.0.6 on 2023-05-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
