# Generated by Django 4.0.6 on 2023-05-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_properties_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='likes',
            new_name='num_of_like',
        ),
    ]
