# Generated by Django 4.0.6 on 2023-05-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_about_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
    ]
