# Generated by Django 4.0.6 on 2023-05-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_userprofile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
