# Generated by Django 4.0.6 on 2023-05-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_userprofile_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_id',
            field=models.IntegerField(null=True),
        ),
    ]
