# Generated by Django 4.0.6 on 2023-05-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_userprofile_id_user_userprofile__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='_id',
        ),
    ]
