# Generated by Django 4.0.6 on 2023-05-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_userprofile__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
