# Generated by Django 4.0.6 on 2023-05-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userprofile_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.userprofile'),
        ),
    ]
