# Generated by Django 4.0.6 on 2023-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_properties_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='properties',
            name='profileImage',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
    ]
