# Generated by Django 4.0.6 on 2023-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_properties_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
