# Generated by Django 4.2 on 2023-05-13 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_properties_image_alter_properties_profileimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
