# Generated by Django 4.2 on 2023-05-13 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_properties_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='id',
        ),
        migrations.AlterField(
            model_name='properties',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
