# Generated by Django 4.0.6 on 2023-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='user_image',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
    ]
