# Generated by Django 4.0.6 on 2023-04-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tenant_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='moving_date',
            new_name='move_in_date',
        ),
    ]
