# Generated by Django 4.0.6 on 2023-04-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tenant_options_tenant_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
    ]
