# Generated by Django 4.2 on 2023-05-12 07:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='user_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
