# Generated by Django 4.0.6 on 2023-04-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
