# Generated by Django 4.0.6 on 2023-05-02 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_booked_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_house',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house'),
        ),
    ]
