# Generated by Django 4.0.6 on 2023-05-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_alter_booked_house_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
