# Generated by Django 4.0.6 on 2023-05-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_category_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
    ]
