# Generated by Django 4.0.6 on 2023-05-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_rename_property_id_likes_house_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owner_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='owner_pic',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
    ]
